### ISSUE TITLE
Middle-clicking search results pre-appends an extra path to URL

### ISSUE THREAD

**Issue by Ukendio** [evaera/moonwave#116]
## Reproduction Steps
1. Go to the API page of any Moonwave generated documentation site.
2. Type something into the search bar / navigation.
3. Middle-click any of the found results.

## Expected behaviour
I expect it to take me to the relevant sections.

## Actual behaviour
Takes me to a page that isn't found.

![image](https://user-images.githubusercontent.com/68000848/176496886-45409f6f-a2fc-4283-8d59-4a7a5504a57a.png)

this issue persists in every doc that was moonwave generated such as:
1. [Matter](https://github.com/evaera/matter)
2. [ClientCast](https://pysephwasntavailable.github.io/ClientCast/api/ClientCast/)
3. [RbxUtil](https://sleitnick.github.io/RbxUtil/)

**Comment by evaera** [comment]
This is a bug in our dependency https://github.com/praveenn77/docusaurus-lunr-search
