### ISSUE TITLE
`Luau` extension files are not recompiled on save

### ISSUE THREAD

**Issue by bubshayz** [evaera/moonwave#122]
The title is self-explanatory - `Luau` extension files are not recompiled upon saving them (after making changes to them). This isn't the case for `Lua` extension files.

### Repro:

- Create a file with `Luau` extension, e.g `test.luau`.
- Add simple class documentation on top of the file, e.g;
  ```lua
  --- @class MyClass
  --- A sample class.
  ```
- Run `moonwave dev`.
- Make changes to the file and save the file.
- Moonwave doesn't recompile.

Repeat the same repro, but on a file with `lua` extension, moonwave will always recompile upon saving the file as expected.

### Workaround:

- Either create a temporary `lua` file and save it when you make a change to a `luau` file OR save a `moonwave.toml` file.

**Comment by evaera** [comment]
https://github.com/evaera/moonwave/blob/master/docusaurus-plugin-moonwave/src/index.js#L230
