### ISSUE TITLE
Module.abc = function() isn't recognized

### ISSUE THREAD

**Issue by DazorPlasma** [evaera/moonwave#139]
```lua
--[=[
	This doesn't work.
]=]
Module.foo = function()
	print("hey")
end

--[=[
	This works.
]=]
function Module.bar()
	print("hello")
end
```

**Comment by YetAnotherClown** [comment]
Blocked by #147, I have a working fix that relies on at full-moon v1.0.0. Support for these anonymous function assignments will be added shortly after the full-moon v1.0.0 pull request is merged.
