### ISSUE TITLE
"moonwave dev" cannot run due to npm security patch

### ISSUE THREAD

**Issue by MiaGobble** [evaera/moonwave#140]
Due to some security patches npm cannot run `moonwave dev`, throwing an error reading `Error: spawn EINVAL`

![Code_roKtRR1N6X](https://github.com/evaera/moonwave/assets/96698128/dc563ff9-ebaf-4be2-8ba2-c1ed0e6825f3)

A workaround for this is to revert to 16.20.2. However, after running `moonwave dev` in that version, I get this error:

![Code_lQZBWorKXY](https://github.com/evaera/moonwave/assets/96698128/48414cdf-9caf-4a8f-bbc6-18eaf45a547b)

```
[ERROR] Error: Command failed: "C:\Users\c5599\AppData\Roaming\nvm\v16.20.2\node_modules\moonwave\dist\bin\moonwave-extractor-1.1.2.exe" extract "C:/Users/c5599/Documents/GitHub/Slap-Battles-Rojo-Transfer/src" --base "C:\Users\c5599\Documents\GitHub\Slap-Battles-Rojo-Transfer"

thread 'main' has overflowed its stack

    at ChildProcess.exithandler (node:child_process:402:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Socket.<anonymous> (node:internal/child_process:458:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:301:12)
```

Is there a workaround for this? If not, hope this gets patched soon 🙏🏻

**Comment by wrello** [comment]
Install nodejs 16. It worked for me.

Source: https://discord.com/channels/385151591524597761/894395472582676502/1236195423773921290

**Comment by MiaGobble** [comment]
> Install nodejs 16. It worked for me.
> 
> Source: https://discord.com/channels/385151591524597761/894395472582676502/1236195423773921290

This does not fix the issue, I mentioned in the issue post that I did that.

> A workaround for this is to revert to 16.20.2. However, after running moonwave dev in that version, I get this error:...

**Comment by MiaGobble** [comment]
As an update, I discovered that it's only an issue for certain games, no idea what the cause is.
