### ISSUE TITLE
moonwave@latest fails to run due to external API returning a null response ("404 not found" message)

### ISSUE THREAD

**Issue by ambergamefam** [evaera/moonwave#144]
I just installed the latest version of moonwave via NPM:
```sh
$ moonwave i -g moonwave
```

Then, running `moonwave dev` returns the following output:
```
Raw response from API: null
Error: 404 Not Found - Could not fetch Moonwave binary
Moonwave: It looks like something went wrong. Check the error output above.
```

It turns out this is caused by moonwave trying to fetch the binary from this endpoint: `https://latest-github-release.eryn.io/evaera/moonwave/v1.1.3`

It looks like version v1.1.3 was pushed to NPM, but v1.1.3 was not added to that endpoint (maybe due to the fact that it's marked as a pre-release).

I was able to work around this by installing `v1.1.2` specifically:

```sh
$ moonwave i -g moonwave@1.1.2
```

**Comment by evaera** [comment]
Should work now
