### ISSUE TITLE
update docusarus to latest version

### ISSUE THREAD

**Issue by RuizuKun-Dev** [evaera/moonwave#149]
![image](https://github.com/user-attachments/assets/ef85ef82-b611-41a2-a57e-392f9df214cd)

I keep getting that message and  already ran `npm i @docusaurus/core@latest @docusaurus/preset-classic@latest`

seems like a problem with moonwave itself?

**Comment by YetAnotherClown** [comment]
This is already resolved and will be released in Moonwave v1.2.0.
